import{S as h,a as y,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const u=document.querySelector(".gallery"),s=document.querySelector(".loader");let f;function m(i){const o=i.map(({webformatURL:t,largeImageURL:l,tags:e,likes:r,views:a,comments:p,downloads:d})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${l}"><img class="gallery-image"src="${t}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="info-item"><b>Likes</b> ${r}</p>
    <p class="info-item"><b>Views</b> ${a}</p>
    <p class="info-item"><b>Comments</b> ${p}</p>
    <p class="info-item"><b>Downloads</b> ${d}</p>
    </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",o),f?f.refresh():f=new h(".gallery a",{captionsData:"alt",captionDelay:250})}function b(){u.innerHTML=""}function L(){s&&(s.classList.add("is-loading"),s.textContent="Loading images, please wait...")}function c(){s&&(s.classList.remove("is-loading"),s.textContent="")}const P="49743900-b0f1cd5437de5205d7989fbc4";function q(i){const o=new URLSearchParams({key:P,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0});return y.get(`https://pixabay.com/api/?${o}`).then(({data:t})=>{t.hits.length===0?(n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c()):(m(t.hits),c())}).catch(t=>{console.log(t),c(),n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})})}const g=document.querySelector(".form"),S=g.querySelector('[name="search-text"]');g.addEventListener("submit",i=>{i.preventDefault();const o=S.value.trim();if(!o){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}b(),L(),q(o).then(t=>{t.length>0?m(t):n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(t=>{console.log(t),n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}).finally(()=>{c()})});
//# sourceMappingURL=index.js.map
