import{S as g,a as y,i as f}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery"),s=document.querySelector(".loader");let l;function h(i){const r=i.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:n,comments:d,downloads:p})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${a}"><img class="gallery-image"src="${o}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="info-item"><b>Likes</b> ${t}</p>
    <p class="info-item"><b>Views</b> ${n}</p>
    <p class="info-item"><b>Comments</b> ${d}</p>
    <p class="info-item"><b>Downloads</b> ${p}</p>
    </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),l?l.refresh():l=new g(".gallery a")}function b(){u.innerHTML=""}function L(){s&&(s.classList.add("is-loading"),s.textContent="Loading...")}function c(){s&&(s.classList.remove("is-loading"),s.textContent="")}const q="49743900-b0f1cd5437de5205d7989fbc4";function P(i){const r=new URLSearchParams({key:q,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0});return y.get(`https://pixabay.com/api/?${r}`).then(({data:o})=>{o.hits.length===0?(f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c()):(h(o.hits),c())}).catch(o=>{console.log(o),c(),f.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})})}const m=document.querySelector(".form"),S=m.querySelector('[name="search-text"]');m.addEventListener("submit",i=>{i.preventDefault();const r=S.value.trim();if(!r){f.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}b(),L(),P(r)});
//# sourceMappingURL=index.js.map
